version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: management-board
    ports:
      - "5000:8080"
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: managementboard
      MYSQL_USER: elias
      MYSQL_PASSWORD: 04yEQqGk
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3706"  # Corrected port mapping
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

  